properties:
  template:
    containers:
    - name: grc-frontend-react
      image: node:18-alpine
      env:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: "8080"
      command:
      - "/bin/sh"
      - "-c"
      - |
        echo "Installing dependencies..."
        apk add --no-cache git
        echo "Cloning repository..."
        git clone https://github.com/adamengleby/grc-ai-platform.git /app
        cd /app
        if [ -d "packages/frontend" ]; then
          cd packages/frontend
        fi
        echo "Installing npm packages..."
        npm install
        echo "Building application..."
        npm run build
        echo "Setting up server..."
        cd dist
        npm init -y
        npm install express
        echo 'const express = require("express"); const path = require("path"); const app = express(); app.use(express.static(".")); app.get("/health", (req, res) => res.json({status: "healthy", service: "GRC Frontend", timestamp: new Date().toISOString()})); app.get("*", (req, res) => res.sendFile(path.join(__dirname, "index.html"))); app.listen(process.env.PORT || 8080, () => console.log("Server running on", process.env.PORT || 8080));' > server.js
        echo "Starting server..."
        node server.js
      resources:
        cpu: 0.5
        memory: 1.0Gi
  configuration:
    ingress:
      external: true
      targetPort: 8080