name = "grc-backend-au"
main = "worker.js"
compatibility_date = "2024-09-24"
compatibility_flags = ["nodejs_compat"]

# Deploy to Australian edge locations automatically

# Environment variables for different stages
[env.production]
name = "grc-backend-au"

[env.staging]
name = "grc-backend-au-staging"

# Bindings for Azure integration (if needed)
# [vars]
# AZURE_OPENAI_ENDPOINT = "your-azure-openai-endpoint"
# AZURE_OPENAI_KEY = "your-key"  # Use Cloudflare secrets for sensitive data