name: Azure Diagnostics

on:
  workflow_dispatch:

jobs:
  diagnose-azure:
    runs-on: ubuntu-latest

    steps:
    - name: Azure Login Test
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Test Azure CLI Access
      run: |
        echo "Testing Azure CLI access..."
        az account show || echo "❌ Azure account access failed"
        az account list-locations --query '[0].name' || echo "❌ Azure locations failed"

    - name: Test Resource Group Access
      run: |
        echo "Testing resource group access..."
        az group list --query '[].name' || echo "❌ Resource group listing failed"

        echo "Attempting to create test resource group..."
        az group create --name rg-test-permissions --location eastus || echo "❌ Cannot create resource groups"

        echo "Cleaning up test resource group..."
        az group delete --name rg-test-permissions --yes --no-wait || echo "Test RG may not exist"

    - name: Check Subscription and Permissions
      run: |
        echo "Current subscription:"
        az account show --query '{subscriptionId:id, name:name, state:state}'

        echo "Available resource providers:"
        az provider list --query '[?namespace==`Microsoft.Web`].{Namespace:namespace, State:registrationState}' || echo "❌ Cannot check providers"

    - name: Test App Service Creation (Dry Run)
      run: |
        echo "Testing App Service creation permissions..."
        az appservice plan create \
          --name test-plan-permissions \
          --resource-group rg-grc-ai-platform-prod \
          --location eastus \
          --sku F1 \
          --is-linux \
          --only-show-errors || echo "❌ Cannot create App Service plans"