properties:
  template:
    containers:
    - image: mcr.microsoft.com/azure-functions/node:4-node20-appservice
      name: grc-frontend-simple
      env:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: "8080"
      - name: VITE_API_BASE_URL
        value: "https://grc-backend-simple.calmmeadow-5080198e.australiasoutheast.azurecontainerapps.io/api/v1"
      command: ["/bin/sh"]
      args: ["-c", "echo 'Setting up GRC Frontend with latest build...' && cat > package.json << 'EOF'\n{\n  \"name\": \"grc-frontend\",\n  \"version\": \"1.0.0\",\n  \"main\": \"server.js\",\n  \"dependencies\": {\n    \"express\": \"^4.19.2\"\n  }\n}\nEOF\necho 'Installing dependencies...' && npm install && echo 'Creating server...' && cat > server.js << 'EOF'\nconst express = require('express');\nconst path = require('path');\nconst app = express();\napp.use(express.static('.'));\napp.get('/health', (req, res) => {\n  res.json({ status: 'healthy', service: 'GRC React Frontend with No MCP Validation', timestamp: new Date().toISOString() });\n});\napp.get('*', (req, res) => {\n  res.sendFile(path.join(__dirname, 'index.html'));\n});\nconst port = process.env.PORT || 8080;\napp.listen(port, () => {\n  console.log('🚀 GRC Frontend (MCP validation removed) on port ' + port);\n});\nEOF\necho 'Downloading latest frontend build without MCP validation...' && curl -s -L -o frontend.zip 'https://github.com/adamengleby/grc-ai-platform/archive/refs/heads/master.zip' && unzip -q frontend.zip && cp -r grc-ai-platform-master/packages/frontend/dist/* . && rm -rf grc-ai-platform-master frontend.zip && echo 'Frontend files deployed - MCP validation removed' && node server.js"]
      resources:
        cpu: 0.5
        memory: 1Gi
    scale:
      minReplicas: 1
      maxReplicas: 3
  configuration:
    ingress:
      external: true
      targetPort: 8080